{% set name = "poetry-core" %}
{% set version = "1.3.1" %}

package:
  name: poetry-core
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poetry-core-{{ version }}.tar.gz
  sha256: f4e68f596ba7560d41f67c705e160a0ed1a061c564cc1f989a5829aa64ea6279
  patches:
    - vcs.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - intreehooks
  run:
    - python >=3.7
    # upstream claims this isn't needed for py>=38 but want to keep this noarch
    # if possible
    - importlib-metadata >=1.7.0

test:
  imports:
    - poetry.core
    - poetry.core._vendor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/poetry-core/
  summary: Core utilities for Poetry
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
