{% set name = "poetry-core" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poetry_core-{{ version }}.tar.gz
  sha256: 514bd33c30e0bf56b0ed44ee15e120d7e47b61ad908b2b1011da68c48a84ada9
  patches:
    - vcs.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    # upstream claims this isn't needed for py>=38 but want to keep this noarch
    # if possible
    - importlib-metadata >=1.7.0

test:
  imports:
    - poetry.core
    - poetry.core._vendor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/poetry-core/
  summary: Core utilities for Poetry
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - xylar
